M48
; DRILL file {KiCad 8.0.2} date 2024-09-12T20:37:15+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-12T20:37:15+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1280
%
G90
G05
T1
X5.1361Y-2.61
T2
X6.3405Y-4.2016
X6.3405Y-4.9496
X6.8917Y-4.2011
X6.8917Y-4.9491
T3
X4.966Y-2.4198
X4.966Y-2.9198
M30
